project:
  name: tracking-and-detection-lab
  seed: 0

paths:
  dataset_path: "" 
  output_root: "./output"
  detections_root: "./data"
  models_root: "/home/lennart/Dokumente/gau/master-thesis/PointPillars/pretrained/epoch_160.pth"
  detection_path: ""
  ground_truth_path: ""
  tracking_path: ""
  logging_path: ./logs
  mmdetection3d_path: "/home/lennart/Dokumente/gau/master-thesis/tracking-and-detection-lab/mmdetection3d"
  config_file: ""

benchmark:
        iou_threshold: 0.5
        class_filter: [1, 2, 3] 

visualizer:
        colour: "Red"

runtime:
  mode: "inference"
  display: false 
  dataset: "KITTI3D"                      
  detector: "pointpillars"                  
  tracker: ""
  datatype: "bin"
  benchmark: true
  
tracker:
        max_age: 0.2
        min_hits: 2
        iou_threshold: 0.5
