project:
  name: tracking-and-detection-lab
  seed: 0

paths:
  dataset_path: "/media/lennart/LaCie/gau/advanced-research-training-applied-system-development/datasets/kitti_3D_object_detection" # absolute or relative to this file
  output_root: "./output"
  detections_root: "./data"
  models_root: "/home/lennart/Dokumente/gau/master-thesis/tracking-and-detection-lab/src/detector/pointnet/models/pointnet_kitti.pth"
  detection_path: "/home/lennart/Dokumente/gau/advanced-research-training-applied-system-development/track-lab/src/data/detr/KITTI-17/det/"
  ground_truth_path: "/home/lennart/Dokumente/gau/advanced-research-training-applied-system-development/track-lab/data/MOT15/train/KITTI-17/gt/gt.txt"
  tracking_path: "/home/lennart/Dokumente/gau/advanced-research-training-applied-system-development/track-lab/src/output/KITTI-17.txt"
  
runtime:
  mode: "train"
  display: false
  dataset: "KITTI-17"                      
  detector: "detr"                  
  tracker: "deepsort"
  datatype: "bin"
  benchmark: true